# Generated by Django 4.2.6 on 2025-07-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Nome da cidade pesquisada', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Data e hora da pesquisa')),
                ('data', models.JSONField(help_text='Dados da resposta da API de clima')),
            ],
            options={
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
